// Code generated by golox-ast. DO NOT EDIT.
package stmt

import (
	"github.com/doeg/golox/golox/token"
)

type StmtVisitor interface {
	VisitExpressionStmt(expr *Expression) (any, error)
	VisitPrintStmt(expr *Print) (any, error)
}

type Stmt interface {
	Accept(StmtVisitor) (any, error)
}

type Expression struct {
	Expression Expr
}

func (e *Expression) Accept(v StmtVisitor) (any, error) {
	return v.VisitExpressionStmt(e)
}

type Print struct {
	Expression Expr
}

func (e *Print) Accept(v StmtVisitor) (any, error) {
	return v.VisitPrintStmt(e)
}
